//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaIscritti
    {
        public int IDSquadra { get; set; }
        public string  IDTorneo { get; set; }
        public int IDAllenatore { get; set; }
        public System.DateTime DataIscrizione { get; set; }
        public bool Cancellata { get; set; }
        public bool WildCard { get; set; }
    }
}
