//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Squadra
    {
        public Squadra()
        {
        }
    
        public int IDSquadra { get; set; }
        public string Atleta1 { get; set; }
        public string Atleta2 { get; set; }
        public bool Accettato { get; set; }
        public string NomeTeam { get; set; }
        public ListaIscritti Iscritto { get; set; } 
    }
}
